### ISSUE TITLE
是否已经修改完成

### ISSUE THREAD

**Issue by nameBai** [WuJunde/werewolf_ai_agents#1]
请问这个修改是否已经完成，目前我的运行似乎有点问题

**Comment by WuJunde** [comment]
我这边可以用了，你是什么问题？

**Comment by nameBai** [comment]
ok了，是一个很棒的工作，已经没有问题了，谢谢你，另外metagpt官方也更新了新版的werewolf

**Comment by WuJunde** [comment]
@GreBai 我们正在做一个大语言模型做游戏强化学习的环境，欢迎关注： https://github.com/WuJunde/CamelGym
